name: YandexGPT AI News - Optimized

on:
  schedule:
    # Запуск каждый час с 04:00 до 16:00 UTC (07:00-19:00 МСК)
    - cron: '0 4-16 * * *'
  workflow_dispatch:
    inputs:
      hour:
        description: 'Час для публикации (4-16 UTC = 7-19 МСК)'
        required: false
        type: choice
        options:
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16

jobs:
  publish-news:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Уменьшили таймаут
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Publish AI News
        env:
          YANDEX_API_KEY: ${{ secrets.YANDEX_API_KEY }}
          YANDEX_FOLDER_ID: ${{ secrets.YANDEX_FOLDER_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: |
          echo "🕐 UTC: $(date -u) • МСК: $(date -d '+3 hours')"
          python src/main.py
