name: News Parser

on:
  workflow_dispatch:
  #schedule:
    #- cron: "0 */6 * * *"   # каждые 6 часов

jobs:
  parser:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run parser
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_USER_ID }}
      run: python news_parser_db.py

    - name: Upload DB artifact
      uses: actions/upload-artifact@v4
      with:
        name: news-db
        path: news.db

    - name: Upload parser log
      uses: actions/upload-artifact@v4
      with:
        name: news-parser-log
        path: news_parser.log
