name: YandexGPT AI News Monitor

on:
  schedule:
    # Запуск каждый час с 06:00 до 18:00 UTC (09:00-21:00 МСК)
    - cron: '0 6-18 * * *'
  workflow_dispatch:
    inputs:
      immediate:
        description: 'Немедленная публикация'
        required: false 
        type: boolean

jobs:
  publish-news:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests schedule

      - name: Publish AI News
        env:
          YANDEX_API_KEY: ${{ secrets.YANDEX_API_KEY }}
          YANDEX_FOLDER_ID: ${{ secrets.YANDEX_FOLDER_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: |
          python src/main.py
